<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SkillSprint.Application\SkillSprint.Application.csproj" />
    <ProjectReference Include="..\SkillSprint.Domain\SkillSprint.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.8.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

</Project>
